import os
from langchain.chains import RetrievalQA
from langchain.chat_models import ChatOpenAI
from langchain.prompts import PromptTemplate
from dotenv import load_dotenv
from langchain.callbacks.base import BaseCallbackHandler

class StreamToAppCallbackHandler(BaseCallbackHandler):
    def __init__(self, stream_function):
        """
        Initialize the callback with a function to handle streamed tokens.
        :param stream_function: A function that takes a token and updates the app's UI.
        """
        self.stream_function = stream_function

    def on_llm_new_token(self, token: str, **kwargs) -> None:
        """
        Called whenever a new token is generated by the model.
        """
        self.stream_function(token)  # Send the token to the app's UI

load_dotenv()

# Initialize GPT-4o model
llm = ChatOpenAI(model_name="gpt-4o", temperature=0.6, streaming=True)

# Function to dynamically add article titles to the system prompt
def add_Articles(articles):
    """
    Generate a system prompt that includes the titles of the articles.
    """
    titles = "\n".join([f"- {article['title']}" for article in articles])
    sys_prompt = (
        "You are a helpful assistant to report the latest news and answer questions "
        "based on the provided context from CBC news articles. Respond naturally and "
        "you are reporting the news as an expert journalist/reporter. "
        "Do not create fake news or provide false information. If possible, answer in markdown format so that "
        "the user can easily catch the gist of the answer. "
        "You have access to the following article titles:\n\n"
        f"{titles}\n\n"
    )
    return sys_prompt

# Function to dynamically create the QA_TEMPLATE
def create_QA_template(articles):
    """
    Create the QA_TEMPLATE dynamically using the articles.
    """
    return add_Articles(articles) + """


Context:
{context}

Question:
{question}

Answer:
"""

# Function to answer questions
def answer_question(query: str, vectorstore, articles: list, stream_function=None) -> str:
    """
    Answer a question using the provided vectorstore and dynamically include article titles in the prompt.
    Stream the response incrementally if a stream_function is provided.
    """
    try:
        # Create a retriever from the provided vectorstore
        retriever = vectorstore.as_retriever(search_kwargs={"k": 5})

        # Dynamically generate the QA_TEMPLATE with the articles
        QA_TEMPLATE = create_QA_template(articles)

        # Create a PromptTemplate with the dynamically generated QA_TEMPLATE
        prompt = PromptTemplate(
            input_variables=["context", "question"],
            template=QA_TEMPLATE
        )

        # Create a new RAG chain with the retriever and dynamic prompt
        qa_chain = RetrievalQA.from_chain_type(
            llm=llm,
            retriever=retriever,
            return_source_documents=False,
            chain_type="stuff",
            chain_type_kwargs={"prompt": prompt}
        )

        # Stream the response incrementally
        if stream_function:
            # Use the callback to stream tokens
            qa_chain.run(query, callbacks=[StreamToAppCallbackHandler(stream_function)])
            return ""  # No need to return the full response since it's streamed
        else:
            # Run the query and return the full response
            result = qa_chain.run(query)
            return f"\n{result}"
    except Exception as e:
        return f"❌ Error answering question: {e}"